### ISSUE TITLE
KB dataset description(s) are not up-to-date

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/dataset-register-entries#3]
The live published metadata for the [NBT dataset](http://data.bibliotheken.nl/doc/dataset/nbt) is not in sync with the dataset description in this repo. Probably the case for all the KB datasets.

**Comment by coret** [comment]
Updated all from data.bibliotheken.nl (still needed because of a circular reference in schema:mainEntityOfPage which need commenting out).

**Comment by EnnoMeijers** [comment]
Thanks Bob! Any idea when KB is going to fix this? @renevoorburg: do you have an idea?
